name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ai-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/ai-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aks-store-demo:ai-service-latest

      - name: Build and push makeline-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/makeline-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aks-store-demo:makeline-service-latest

      - name: Build and push order-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/order-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aks-store-demo:order-service-latest