name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: alexisbarros00/aks-store-app:latest  # Update this

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Install Argo CD CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install-latest.sh | bash

      - name: Login to Argo CD
        run: argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync the application
        run: argocd app sync aks-store  # Update this
